apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 2560m
      memory: 1Gi
    requests:
      cpu: 2048m
      memory: 1Gi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/sykmeldinger-backend
        mountPath: /secrets/azuread/sykmeldinger-backend
      - kvPath: serviceuser/data/prod/srvsykm-backend
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/sykmeldinger-backend/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://sykmeldinger-backend.nais.adeo.no"
  webproxy: true
  envFrom:
    - configmap: loginservice-idporten
    - secret: sykmeldinger-backend-redis-password
  env:
    - name: JWT_ISSUER
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0
    - name: STS_OIDC_ISSUER
      value: https://security-token-service.nais.adeo.no
    - name: EREG_URL
      value: https://ereg-services.intern.nav.no
    - name: AAREG_URL
      value: https://aareg-services.intern.nav.no
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.intern.nav.no
