apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 80
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 2560m
      memory: 2048Mi
    requests:
      cpu: 2048m
      memory: 1792Mi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: prod-gcp
    outbound:
      rules:
        - application: sykmeldinger-backend-redis
        - application: narmesteleder
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: ereg-services.prod-fss-pub.nais.io
        - host: aareg-services.prod-fss-pub.nais.io
        - host: syfosmregister.prod-fss-pub.nais.io
  vault:
    enabled: false
  ingresses:
    - "https://sykmeldinger-backend.nav.no"
  webproxy: false
  envFrom:
    - configmap: loginservice-idporten
    - secret: sykmeldinger-backend-redis-password
  env:
    - name: EREG_URL
      value: https://ereg-services.prod-fss-pub.nais.io
    - name: AAREG_URL
      value: https://aareg-services.prod-fss-pub.nais.io
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.nav.no
    - name: SYFOSMREGISTER_URL
      value: https://syfosmregister.prod-fss-pub.nais.io
    - name: SYFOSMREGISTER_AUDIENCE
      value: prod-fss:teamsykmelding:syfosmregister
    - name: PDL_AUDIENCE
      value: prod-fss:pdl:pdl-api
    - name: AAREG_AUDIENCE
      value: prod-fss:arbeidsforhold:aareg-services-nais
    - name: NARMESTELEDER_AUDIENCE
      value: prod-gcp:teamsykmelding:narmesteleder
    - name: ALLOWED_ORIGIN
      value: www.nav.no
