apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: sykmeldinger-db-instance
        type: POSTGRES_14
        diskSize: 10
        tier: db-custom-2-5120
        databases:
          - name: sykmeldinger
            envVarPrefix: DB
            users:
              - name: sykmeldinger-kafka-user
        diskAutoresize: true
        highAvailability: true
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1028Mi
    requests:
      cpu: 50m
      memory: 600Mi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: ereg-services.prod-fss-pub.nais.io
        - host: aareg-services.prod-fss-pub.nais.io
    inbound:
      rules:
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: ditt-sykefravaer
          namespace: flex
          cluster: prod-gcp
        - application: sykepengesoknad
          namespace: flex
          cluster: prod-gcp
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  env:
    - name: EREG_URL
      value: https://ereg-services.prod-fss-pub.nais.io
    - name: AAREG_URL
      value: https://aareg-services.prod-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default
