apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: sykmeldinger-db-instance
        type: POSTGRES_14
        diskSize: 10
        tier: db-custom-2-5120
        databases:
          - name: sykmeldinger
            envVarPrefix: DB
            users:
              - name: sykmeldinger-kafka-user
        diskAutoresize: true
        highAvailability: true
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 5
    max: 8
    cpuThresholdPercentage: 80
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 400m
      memory: 1028Mi
    requests:
      cpu: 200m
      memory: 768Mi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: ditt-sykefravaer
          namespace: flex
          cluster: prod-gcp
        - application: sykepengesoknad
          namespace: flex
          cluster: prod-gcp
  secureLogs:
    enabled: true
  ingresses:
    - "https://sykmeldinger-backend.nav.no"
  env:
    - name: ALLOWED_ORIGIN
      value: www.nav.no
