apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 2560m
      memory: 2048Mi
    requests:
      cpu: 2048m
      memory: 1792Mi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: prod-gcp
  vault:
    enabled: false
  ingresses:
    - "https://sykmeldinger-backend.nais.adeo.no"
    - "https://sykmeldinger-backend.intern.nav.no"
  webproxy: true
  envFrom:
    - configmap: loginservice-idporten
    - secret: sykmeldinger-backend-redis-password
  env:
    - name: EREG_URL
      value: https://ereg-services.intern.nav.no
    - name: AAREG_URL
      value: https://aareg-services.intern.nav.no
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.intern.nav.no
    - name: SYFOSMREGISTER_AUDIENCE
      value: prod-fss:teamsykmelding:syfosmregister
    - name: PDL_AUDIENCE
      value: prod-fss:pdl:pdl-api
    - name: AAREG_AUDIENCE
      value: prod-fss:arbeidsforhold:aareg-services-nais
    - name: NARMESTELEDER_AUDIENCE
      value: prod-gcp:teamsykmelding:narmesteleder
