apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: debug-dings
          namespace: plattformsikkerhet
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/sykmeldinger-backend
        mountPath: /secrets/azuread/sykmeldinger-backend
      - kvPath: serviceuser/data/dev/srvsykm-backend
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/sykmeldinger-backend/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://sykmeldinger-backend.nais.preprod.local"
  webproxy: true
  envFrom:
    - configmap: loginservice-idporten
    - secret: sykmeldinger-backend-redis-password
  env:
    - name: JWT_ISSUER
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0
    - name: STS_OIDC_ISSUER
      value: https://security-token-service.nais.preprod.local
    - name: EREG_URL
      value: https://ereg-services-q1.dev.intern.nav.no
    - name: AAREG_URL
      value: https://aareg-services-q1.dev.intern.nav.no
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.dev.intern.nav.no
    - name: SYFOSMREGISTER_AUDIENCE
      value: dev-fss:teamsykmelding:syfosmregister
    - name: PDL_AUDIENCE
      value: dev-fss:pdl:pdl-api
    - name: AAREG_AUDIENCE
      value: dev-fss:arbeidsforhold:aareg-services-nais-q1
    - name: NARMESTELEDER_AUDIENCE
      value: dev-gcp:teamsykmelding:narmesteleder
