apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
  ingresses:
    - "https://sykmeldinger-backend.nais.preprod.local"
  webproxy: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: JWT_ISSUER
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0
    - name: CLIENT_ID
      value: 543ceb1e-eb69-4089-9458-bdec61160afa
    - name: ALLOWED_APP_IDS
      value: 543ceb1e-eb69-4089-9458-bdec61160afa
    - name: STS_OIDC_ISSUER
      value: https://security-token-service.nais.preprod.local
    - name: STS_OIDC_AUDIENCE
      value: preprod.local

