apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: sykmeldinger-db-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: sykmeldinger
            envVarPrefix: DB
            users:
              - name: sykmeldinger-kafka-user
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        tier: db-f1-micro
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 30m
      memory: 300Mi
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: ereg-services-q1.dev-fss-pub.nais.io
        - host: aareg-services-q1.dev-fss-pub.nais.io
    inbound:
      rules:
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: ditt-sykefravaer
          namespace: flex
          cluster: dev-gcp
        - application: sykepengesoknad
          namespace: flex
          cluster: dev-gcp
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  env:
    - name: EREG_URL
      value: https://ereg-services-q1.dev-fss-pub.nais.io
    - name: AAREG_URL
      value: https://aareg-services-q1.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: api://dev-fss.arbeidsforhold.aareg-services-nais-q1/.default
