apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykmelding
  name: sykmeldinger-backend-redis
  namespace: teamsykmelding
spec:
  image: navikt/secure-redis:5.0.3-alpine-2
  port: 6379
  replicas:
    min: 1
    max: 4
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  service:
    port: 6379
  vault:
    enabled: true