apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykmelding
  name: sykmeldinger-backend-redis
  namespace: teamsykmelding
  annotations:
    nais.io/run-as-group: "0" # Fix permissions for bitnami/redis
    nais.io/read-only-file-system: "false" # Fix permissions for bitnami/redis
spec:
  image: bitnami/redis:latest # or a custom Redis-image
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: sykmeldinger-backend-redis-password

---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykmelding
  name: sykmeldinger-backend-redisexporter
  namespace: teamsykmelding
spec:
  image: oliver006/redis_exporter:latest
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  liveness:
    path: /health
  env:
    - name: REDIS_ADDR
      value: sykmeldinger-backend-redis:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
  envFrom:
    - secret: sykmeldinger-backend-redis-password
